In [2]:
using LinearAlgebra

### Resolve Diagonal

In [96]:
# Resolve diagonal
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz diagonal
ENTRADA: Matriz A, vetor b
SAIDA: vetor x, solucao do sistema
"""

function resolve_diagonal(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # Dividindo o valor de cada linha de b pelos valores na diagonal de A
    for i = 1:rows
        x[i] = b[i] / A[i,i]
    end
    
    return x
end

resolve_diagonal (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [112]:
A = [2  0   0;
     0  7   0;
     0  0 -11]

b = [-6, 7, 110]

x = resolve_diagonal(A, b)

norm(A*x - b)

0.0

#### Exemplo 2 (n = 5)

In [113]:
n = 5
A = Diagonal(rand(5,5))

b = rand(5)

x = resolve_diagonal(A, b)

norm(A * x - b)

0.0

#### Exemplo 3 (n = 20)

In [114]:
n = 20
A = Diagonal(rand(n, n))
b = rand(n)
x = resolve_diagonal(A, b)
norm(A*x - b)

5.721958498152797e-17

### Resolve Triangular Superior

In [121]:
# Resolve triangular superior
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz triangular superior.
        Ou seja, todos os elementos abaixo da diagonal estao zerados.
ENTRADA: Matriz A, vetor b
SAIDA: vetor x, solucao do sistema
"""

function resolve_triangular_superior(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # substituindo em cada linha, de baixo para cima
    for i = rows:-1:1
        x[i] = b[i]  # pegamos o bᵢ
        for j = i+1:cols
            x[i] -= A[i, j] * x[j]  # subtraimos de bᵢ todos os x's que ja 
                                    # foram calculados (multiplicados pelos coeficientes)
        end
        x[i] = x[i] / A[i, i]  # Dividimos o resultado pelo coeficiente de xᵢ
    end
    
    return x
end

resolve_triangular_superior (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [124]:
A = [-2    7  19;
      0  0.5 -10;
      0    0   3]

3×3 Matrix{Float64}:
 -2.0  7.0   19.0
  0.0  0.5  -10.0
  0.0  0.0    3.0

In [125]:
b = [2, 8.5, -11]

3-element Vector{Float64}:
   2.0
   8.5
 -11.0

In [126]:
x = resolve_triangular_superior(A, b)

3-element Vector{Float64}:
 -233.0
  -56.33333333333333
   -3.6666666666666665

In [127]:
norm(A*x - b)

2.842170943040401e-14

#### Exemplo 2 (n = 5)

In [130]:
n = 5
A = UpperTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_superior(A, b)
norm(A*x - b)

1.2412670766236366e-16

#### Exemplo 3 (n = 20)

In [137]:
n = 20
A = UpperTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_superior(A, b)
norm(A*x - b)

7.405661942207508e-14

### Resolve Triangular Inferior

In [138]:
# Resolve triangular inferior
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz triangular inferior.
        Ou seja, todos os elementos acima da diagonal estao zerados.
ENTRADA: Matriz A, vetor b
SAIDA: vetor x, solucao do sistema
"""

function resolve_triangular_inferior(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # substituindo em cada linha, de cima para baixo
    for i = 1:rows
        x[i] = b[i]  # pegamos o bᵢ
        for j = i-1:-1:1
            x[i] -= A[i, j] * x[j]  # subtraimos de bᵢ todos os x's que ja 
                                    # foram calculados (multiplicados pelos coeficientes)
        end
        x[i] = x[i] / A[i, i]  # Dividimos o resultado pelo coeficiente de xᵢ
    end
    
    return x
end

resolve_triangular_inferior (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [140]:
A = [  9    0   0;
      -7    1   0;
    56.3   85  -2]

3×3 Matrix{Float64}:
  9.0   0.0   0.0
 -7.0   1.0   0.0
 56.3  85.0  -2.0

In [141]:
b = [30, 2.75, -4.1]

3-element Vector{Float64}:
 30.0
  2.75
 -4.1

In [142]:
x = resolve_triangular_inferior(A, b)

3-element Vector{Float64}:
    3.3333333333333335
   26.083333333333336
 1204.425

In [143]:
norm(A*x - b)

9.059419880941277e-14

#### Exemplo 2 (n = 5)

In [147]:
n = 5
A = LowerTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_inferior(A, b)
norm(A*x - b)

1.4936523181711914e-15

#### Exemplo 3 (n = 20)

In [150]:
n = 20
A = LowerTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_inferior(A, b)
norm(A*x - b)

2.2978454670130187e-13

### Eliminação Gaussiana

In [77]:
# Eliminacao gaussiana
"""
RESUMO: Funçao que executa a eliminacao gaussiana em uma matriz A e um vetor b.
ENTRADA: Matriz A, vetor b
SAIDA: Nada
OBS: Modifica as entradas!
"""

function elim_gauss!(A, b)
    rows, cols = size(A)
    for j = 1:cols
        non_zero_cols = j+1:cols
        for i = j+1:rows
            mᵢⱼ = A[i, j] / A[j, j]  # multiplicador que vai zerar a coluna
            A[i, non_zero_cols] -= mᵢⱼ * A[j, non_zero_cols]  # subtracao das linhas de A
            A[i, j] = 0  # zera cada elemento abaixo do pivô na coluna j
            b[i] -= mᵢⱼ * b[j]  # subtracao das linhas de b
        end
    end
end

elim_gauss! (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [151]:
n = 3
A = rand(n,n)
Acopy = copy(A)

3×3 Matrix{Float64}:
 0.736623  0.239938  0.617541
 0.779964  0.997659  0.940925
 0.258513  0.718092  0.690691

In [152]:
b = rand(n)
bcopy = copy(b)

3-element Vector{Float64}:
 0.743925127215534
 0.9520421320209136
 0.5839332294894266

In [153]:
elim_gauss!(A, b)
A

3×3 Matrix{Float64}:
 0.736623  0.239938  0.617541
 0.0       0.743604  0.287049
 0.0       0.0       0.229273

In [154]:
b

3-element Vector{Float64}:
 0.743925127215534
 0.16434625973852302
 0.18276026232875353

In [155]:
# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

0.0

#### Exemplo 2 (n = 5, x random)

In [156]:
n = 5

5

In [168]:
A = rand(n,n)
Acopy = copy(A)

5×5 Matrix{Float64}:
 0.0663475  0.769471   0.0478637  0.183234   0.325281
 0.580215   0.0869982  0.603236   0.958968   0.895386
 0.215092   0.770959   0.937615   0.873565   0.244566
 0.556883   0.231775   0.695685   0.0219232  0.570939
 0.713341   0.1931     0.911457   0.555587   0.340926

In [169]:
b = rand(n)
bcopy = copy(b)

5-element Vector{Float64}:
 0.5324494120906187
 0.14924966608840862
 0.9664684719650702
 0.7191252708108491
 0.26215402299813406

In [170]:
elim_gauss!(A, b)
A

5×5 Matrix{Float64}:
 0.0663475   0.769471  0.0478637   0.183234   0.325281
 0.0        -6.64211   0.184663   -0.643429  -1.94923
 0.0         0.0       0.734527    0.446506  -0.304148
 0.0         0.0       0.0        -0.986296  -0.281921
 0.0         0.0       0.0         0.0       -0.50337

In [171]:
b

5-element Vector{Float64}:
  0.5324494120906187
 -4.507073732545481
  0.40988187432434997
  0.4078382554327967
 -0.3804075388738102

In [172]:
# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

7.711855592701269e-16

#### Exemplo 3 (n = 20, x random)

In [178]:
n = 20
A = rand(n,n)
Acopy = copy(A)
b = rand(n)
bcopy = copy(b)
elim_gauss!(A, b)

# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

1.0559537520802596e-14