In [10]:
using LinearAlgebra

### Resolve Diagonal

In [96]:
# Resolve diagonal
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz diagonal
ENTRADA: Matriz A, vetor b
SAIDA: vetor x, solucao do sistema
"""

function resolve_diagonal(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # Dividindo o valor de cada linha de b pelos valores na diagonal de A
    for i = 1:rows
        x[i] = b[i] / A[i,i]
    end
    
    return x
end

resolve_diagonal (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [112]:
A = [2  0   0;
     0  7   0;
     0  0 -11]

b = [-6, 7, 110]

x = resolve_diagonal(A, b)

norm(A*x - b)

0.0

#### Exemplo 2 (n = 5)

In [113]:
n = 5
A = Diagonal(rand(5,5))

b = rand(5)

x = resolve_diagonal(A, b)

norm(A * x - b)

0.0

#### Exemplo 3 (n = 20)

In [114]:
n = 20
A = Diagonal(rand(n, n))
b = rand(n)
x = resolve_diagonal(A, b)
norm(A*x - b)

5.721958498152797e-17

### Resolve Triangular Superior

In [8]:
# Resolve triangular superior
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz triangular superior.
        Ou seja, todos os elementos abaixo da diagonal estao zerados.
ENTRADA: Matriz A, vetor b
SAIDA: vetor x, solucao do sistema
"""

function resolve_triangular_superior(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # substituindo em cada linha, de baixo para cima
    for i = rows:-1:1
        x[i] = b[i]  # pegamos o bᵢ
        for j = i+1:cols
            x[i] -= A[i, j] * x[j]  # subtraimos de bᵢ todos os x's que ja 
                                    # foram calculados (multiplicados pelos coeficientes)
        end
        x[i] = x[i] / A[i, i]  # Dividimos o resultado pelo coeficiente de xᵢ
    end
    
    return x
end

resolve_triangular_superior (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [124]:
A = [-2    7  19;
      0  0.5 -10;
      0    0   3]

3×3 Matrix{Float64}:
 -2.0  7.0   19.0
  0.0  0.5  -10.0
  0.0  0.0    3.0

In [125]:
b = [2, 8.5, -11]

3-element Vector{Float64}:
   2.0
   8.5
 -11.0

In [126]:
x = resolve_triangular_superior(A, b)

3-element Vector{Float64}:
 -233.0
  -56.33333333333333
   -3.6666666666666665

In [127]:
norm(A*x - b)

2.842170943040401e-14

#### Exemplo 2 (n = 5)

In [130]:
n = 5
A = UpperTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_superior(A, b)
norm(A*x - b)

1.2412670766236366e-16

#### Exemplo 3 (n = 20)

In [137]:
n = 20
A = UpperTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_superior(A, b)
norm(A*x - b)

7.405661942207508e-14

### Resolve Triangular Inferior

In [138]:
# Resolve triangular inferior
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz triangular inferior.
        Ou seja, todos os elementos acima da diagonal estao zerados.
ENTRADA: Matriz A, vetor b
SAIDA: vetor x, solucao do sistema
"""

function resolve_triangular_inferior(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # substituindo em cada linha, de cima para baixo
    for i = 1:rows
        x[i] = b[i]  # pegamos o bᵢ
        for j = i-1:-1:1
            x[i] -= A[i, j] * x[j]  # subtraimos de bᵢ todos os x's que ja 
                                    # foram calculados (multiplicados pelos coeficientes)
        end
        x[i] = x[i] / A[i, i]  # Dividimos o resultado pelo coeficiente de xᵢ
    end
    
    return x
end

resolve_triangular_inferior (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [140]:
A = [  9    0   0;
      -7    1   0;
    56.3   85  -2]

3×3 Matrix{Float64}:
  9.0   0.0   0.0
 -7.0   1.0   0.0
 56.3  85.0  -2.0

In [141]:
b = [30, 2.75, -4.1]

3-element Vector{Float64}:
 30.0
  2.75
 -4.1

In [142]:
x = resolve_triangular_inferior(A, b)

3-element Vector{Float64}:
    3.3333333333333335
   26.083333333333336
 1204.425

In [143]:
norm(A*x - b)

9.059419880941277e-14

#### Exemplo 2 (n = 5)

In [147]:
n = 5
A = LowerTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_inferior(A, b)
norm(A*x - b)

1.4936523181711914e-15

#### Exemplo 3 (n = 20)

In [150]:
n = 20
A = LowerTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_inferior(A, b)
norm(A*x - b)

2.2978454670130187e-13

### Eliminação Gaussiana

In [2]:
# Eliminacao gaussiana
"""
RESUMO: Funçao que executa a eliminacao gaussiana em uma matriz A e um vetor b.
ENTRADA: Matriz A, vetor b
SAIDA: Nada
OBS: Modifica as entradas!
"""

function eliminacao_gaussiana(A, b)
    rows, cols = size(A)
    for j = 1:cols
        non_zero_cols = j+1:cols
        for i = j+1:rows
            mᵢⱼ = A[i, j] / A[j, j]  # multiplicador que vai zerar a coluna
            A[i, non_zero_cols] -= mᵢⱼ * A[j, non_zero_cols]  # subtracao das linhas de A
            A[i, j] = 0  # zera cada elemento abaixo do pivô na coluna j
            b[i] -= mᵢⱼ * b[j]  # subtracao das linhas de b
        end
    end
end

eliminacao_gaussiana (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [3]:
n = 3
A = rand(n,n)
Acopy = copy(A)

3×3 Matrix{Float64}:
 0.202406  0.673815  0.880767
 0.587993  0.708312  0.0878447
 0.871601  0.163057  0.278384

In [4]:
b = rand(n)
bcopy = copy(b)

3-element Vector{Float64}:
 0.8128419958346671
 0.18778020257382844
 0.29418940502129476

In [5]:
eliminacao_gaussiana(A, b)
A

3×3 Matrix{Float64}:
 0.202406   0.673815   0.880767
 0.0       -1.24913   -2.4708
 0.0        0.0        1.90247

In [6]:
b

3-element Vector{Float64}:
  0.8128419958346671
 -2.173538677426604
  1.5590775743480592

In [11]:
# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

2.9893669801409083e-16

#### Exemplo 2 (n = 5, x random)

In [12]:
n = 5

5

In [13]:
A = rand(n,n)
Acopy = copy(A)

5×5 Matrix{Float64}:
 0.447115   0.526316  0.438287  0.978176  0.454452
 0.601031   0.652873  0.988625  0.35596   0.373821
 0.68519    0.700868  0.463585  0.643119  0.422305
 0.890906   0.479626  0.684703  0.453157  0.0877369
 0.0572552  0.548967  0.323097  0.759533  0.897974

In [14]:
b = rand(n)
bcopy = copy(b)

5-element Vector{Float64}:
 0.5640261287581383
 0.8292528488448687
 0.6969664395383763
 0.7414681127930645
 0.44060932503869843

In [15]:
eliminacao_gaussiana(A, b)
A

5×5 Matrix{Float64}:
 0.447115   0.526316    0.438287   0.978176   0.454452
 0.0       -0.0546233   0.399461  -0.958946  -0.237073
 0.0        0.0        -0.981017   0.999619   0.184598
 0.0        0.0         0.0        4.06196    0.833536
 0.0        0.0         0.0        0.0        0.275119

In [16]:
b

5-element Vector{Float64}:
  0.5640261287581383
  0.07106466711198633
 -0.30489362439098844
  0.22929438383551992
  0.04090904190613345

In [17]:
# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

1.1102230246251565e-16

#### Exemplo 3 (n = 20, x random)

In [18]:
n = 20
A = rand(n,n)
Acopy = copy(A)
b = rand(n)
bcopy = copy(b)
eliminacao_gaussiana(A, b)

# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

8.897729340113409e-15

### Resolve Cheia

In [19]:
# Resolve cheia
"""
RESUMO: Resolve um sistema linear com uma matriz quadrada "cheia".
        Ou seja, que nao é triangular nem diagonal.
ENTRADA: Matriz A, vetor b
SAIDA: Vetor x, solucao do sistema.
OBS: Modifica as entradas!
"""

function resolve_cheia(A, b)
    eliminacao_gaussiana(A,b)
    x = resolve_triangular_superior(A,b)
    return x
end

resolve_cheia (generic function with 1 method)

#### Exemplo 3 (n = 20)

In [20]:
n = 20
A = rand(n,n)
Acopy = copy(A)
b = rand(n)
bcopy = copy(b)
x = resolve_cheia(A, b)
norm(Acopy * x - bcopy)

1.9303918037323056e-14