In [10]:
using LinearAlgebra

### Resolve Diagonal

In [96]:
# Resolve diagonal
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz diagonal
ENTRADA: Matriz A, vetor b
SAIDA: vetor x (solucao do sistema)
"""

function resolve_diagonal(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # Dividindo o valor de cada linha de b pelos valores na diagonal de A
    for i = 1:rows
        x[i] = b[i] / A[i,i]
    end
    
    return x
end

resolve_diagonal (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [112]:
A = [2  0   0;
     0  7   0;
     0  0 -11]

b = [-6, 7, 110]

x = resolve_diagonal(A, b)

norm(A*x - b)

0.0

#### Exemplo 2 (n = 5)

In [113]:
n = 5
A = Diagonal(rand(5,5))

b = rand(5)

x = resolve_diagonal(A, b)

norm(A * x - b)

0.0

#### Exemplo 3 (n = 20)

In [114]:
n = 20
A = Diagonal(rand(n, n))
b = rand(n)
x = resolve_diagonal(A, b)
norm(A*x - b)

5.721958498152797e-17

### Resolve Triangular Superior

In [8]:
# Resolve triangular superior
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz triangular superior.
        Ou seja, todos os elementos abaixo da diagonal estao zerados.
ENTRADA: Matriz A, vetor b
SAIDA: vetor x (solucao do sistema)
"""

function resolve_triangular_superior(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # substituindo em cada linha, de baixo para cima
    for i = rows:-1:1
        x[i] = b[i]  # pegamos o bᵢ
        for j = i+1:cols
            x[i] -= A[i, j] * x[j]  # subtraimos de bᵢ todos os x's que ja 
                                    # foram calculados (multiplicados pelos coeficientes)
        end
        x[i] = x[i] / A[i, i]  # Dividimos o resultado pelo coeficiente de xᵢ
    end
    
    return x
end

resolve_triangular_superior (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [124]:
A = [-2    7  19;
      0  0.5 -10;
      0    0   3]

3×3 Matrix{Float64}:
 -2.0  7.0   19.0
  0.0  0.5  -10.0
  0.0  0.0    3.0

In [125]:
b = [2, 8.5, -11]

3-element Vector{Float64}:
   2.0
   8.5
 -11.0

In [126]:
x = resolve_triangular_superior(A, b)

3-element Vector{Float64}:
 -233.0
  -56.33333333333333
   -3.6666666666666665

In [127]:
norm(A*x - b)

2.842170943040401e-14

#### Exemplo 2 (n = 5)

In [130]:
n = 5
A = UpperTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_superior(A, b)
norm(A*x - b)

1.2412670766236366e-16

#### Exemplo 3 (n = 20)

In [137]:
n = 20
A = UpperTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_superior(A, b)
norm(A*x - b)

7.405661942207508e-14

### Resolve Triangular Inferior

In [109]:
# Resolve triangular inferior
""""
RESUMO: Resolve um sistema linear Ax=b que tenha uma matriz triangular inferior.
        Ou seja, todos os elementos acima da diagonal estao zerados.
ENTRADA: Matriz A, vetor b
SAIDA: vetor x (solucao do sistema)
"""

function resolve_triangular_inferior(A, b)
    rows, cols = size(A)
    
    # verifica se a matriz é quadrada
    if rows != cols
        error("A matriz deve ser quadrada!")
    end
    
    # Inicializa o vetor solucao
    x = zeros(rows)
    
    # Calcula cada elemento do vetor x
    # substituindo em cada linha, de cima para baixo
    for i = 1:rows
        x[i] = b[i]  # pegamos o bᵢ
        for j = i-1:-1:1
            x[i] -= A[i, j] * x[j]  # subtraimos de bᵢ todos os x's que ja 
                                    # foram calculados (multiplicados pelos coeficientes)
        end
        x[i] = x[i] / A[i, i]  # Dividimos o resultado pelo coeficiente de xᵢ
    end
    
    return x
end

resolve_triangular_inferior (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [140]:
A = [  9    0   0;
      -7    1   0;
    56.3   85  -2]

3×3 Matrix{Float64}:
  9.0   0.0   0.0
 -7.0   1.0   0.0
 56.3  85.0  -2.0

In [141]:
b = [30, 2.75, -4.1]

3-element Vector{Float64}:
 30.0
  2.75
 -4.1

In [142]:
x = resolve_triangular_inferior(A, b)

3-element Vector{Float64}:
    3.3333333333333335
   26.083333333333336
 1204.425

In [143]:
norm(A*x - b)

9.059419880941277e-14

#### Exemplo 2 (n = 5)

In [147]:
n = 5
A = LowerTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_inferior(A, b)
norm(A*x - b)

1.4936523181711914e-15

#### Exemplo 3 (n = 20)

In [150]:
n = 20
A = LowerTriangular(rand(n,n))
b = rand(n)
x = resolve_triangular_inferior(A, b)
norm(A*x - b)

2.2978454670130187e-13

### Eliminação Gaussiana

In [2]:
# Eliminacao gaussiana
"""
RESUMO: Funçao que executa a eliminacao gaussiana em uma matriz A e um vetor b.
ENTRADA: Matriz A, vetor b
SAIDA: Nada
OBS: Modifica as entradas!
"""

function eliminacao_gaussiana(A, b)
    rows, cols = size(A)
    for j = 1:cols
        non_zero_cols = j+1:cols
        for i = j+1:rows
            mᵢⱼ = A[i, j] / A[j, j]  # multiplicador que vai zerar a coluna
            A[i, non_zero_cols] -= mᵢⱼ * A[j, non_zero_cols]  # subtracao das linhas de A
            A[i, j] = 0  # zera cada elemento abaixo do pivô na coluna j
            b[i] -= mᵢⱼ * b[j]  # subtracao das linhas de b
        end
    end
end

eliminacao_gaussiana (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [3]:
n = 3
A = rand(n,n)
Acopy = copy(A)

3×3 Matrix{Float64}:
 0.202406  0.673815  0.880767
 0.587993  0.708312  0.0878447
 0.871601  0.163057  0.278384

In [4]:
b = rand(n)
bcopy = copy(b)

3-element Vector{Float64}:
 0.8128419958346671
 0.18778020257382844
 0.29418940502129476

In [5]:
eliminacao_gaussiana(A, b)
A

3×3 Matrix{Float64}:
 0.202406   0.673815   0.880767
 0.0       -1.24913   -2.4708
 0.0        0.0        1.90247

In [6]:
b

3-element Vector{Float64}:
  0.8128419958346671
 -2.173538677426604
  1.5590775743480592

In [11]:
# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

2.9893669801409083e-16

#### Exemplo 2 (n = 5, x random)

In [12]:
n = 5

5

In [13]:
A = rand(n,n)
Acopy = copy(A)

5×5 Matrix{Float64}:
 0.447115   0.526316  0.438287  0.978176  0.454452
 0.601031   0.652873  0.988625  0.35596   0.373821
 0.68519    0.700868  0.463585  0.643119  0.422305
 0.890906   0.479626  0.684703  0.453157  0.0877369
 0.0572552  0.548967  0.323097  0.759533  0.897974

In [14]:
b = rand(n)
bcopy = copy(b)

5-element Vector{Float64}:
 0.5640261287581383
 0.8292528488448687
 0.6969664395383763
 0.7414681127930645
 0.44060932503869843

In [15]:
eliminacao_gaussiana(A, b)
A

5×5 Matrix{Float64}:
 0.447115   0.526316    0.438287   0.978176   0.454452
 0.0       -0.0546233   0.399461  -0.958946  -0.237073
 0.0        0.0        -0.981017   0.999619   0.184598
 0.0        0.0         0.0        4.06196    0.833536
 0.0        0.0         0.0        0.0        0.275119

In [16]:
b

5-element Vector{Float64}:
  0.5640261287581383
  0.07106466711198633
 -0.30489362439098844
  0.22929438383551992
  0.04090904190613345

In [17]:
# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

1.1102230246251565e-16

#### Exemplo 3 (n = 20, x random)

In [18]:
n = 20
A = rand(n,n)
Acopy = copy(A)
b = rand(n)
bcopy = copy(b)
eliminacao_gaussiana(A, b)

# Testar (resolvendo o sistema)
x = resolve_triangular_superior(A, b)
norm(Acopy * x - bcopy)

8.897729340113409e-15

### Resolve Cheia

In [19]:
# Resolve cheia
"""
RESUMO: Resolve um sistema linear com uma matriz quadrada "cheia".
        Ou seja, que nao é triangular nem diagonal.
        Primeiro aplicamos a eliminacao gaussiana e depois resolvemos o sistema 
        com a matriz triangular superior.
ENTRADA: Matriz A, vetor b
SAIDA: Vetor x (solucao do sistema)
OBS: Modifica as entradas!
"""

function resolve_cheia(A, b)
    eliminacao_gaussiana(A,b)
    x = resolve_triangular_superior(A,b)
    return x
end

resolve_cheia (generic function with 1 method)

#### Exemplo 1 (n = 3)

In [33]:
A = [2   -4      1;
     9   18  -7.34;
     0  0.2     45]
Acopy = copy(A)

3×3 Matrix{Float64}:
 2.0  -4.0   1.0
 9.0  18.0  -7.34
 0.0   0.2  45.0

In [34]:
b = [-1, 84, 4.333]
bcopy = copy(b)

3-element Vector{Float64}:
 -1.0
 84.0
  4.333

In [35]:
x = resolve_cheia(A, b)

3-element Vector{Float64}:
 4.43011538689126
 2.486367285350796
 0.08523836762066314

In [36]:
norm(Acopy * x - bcopy)

0.0

#### Exemplo 2 (n = 5)

In [37]:
n = 5
A = rand(n,n)
Acopy = copy(A)
b = rand(n)
bcopy = copy(b)
x = resolve_cheia(A, b)
norm(Acopy * x - bcopy)

6.568167990716596e-16

#### Exemplo 3 (n = 20)

In [20]:
n = 20
A = rand(n,n)
Acopy = copy(A)
b = rand(n)
bcopy = copy(b)
x = resolve_cheia(A, b)
norm(Acopy * x - bcopy)

1.9303918037323056e-14

### Decomposição LU 

In [81]:
# Decomposicao LU
"""
RESUMO: Aplica a eliminacao gaussiana na matriz e salva os multiplicadores utilizados
        para decompor uma matriz A em uma matriz triangular inferior L(Lower) e uma matriz
        triangular superior U(Upper). A matriz L pode ser utilizada para aplicar a eliminacao
        gaussiana em um vetor com complexidade O(n^2) em vez de O(n^3).
ENTRADA: Matriz A
SAIDA: Matriz L e matriz U
"""
function decomposicao_LU(A)
    rows, cols = size(A)
    U = copy(A)
    # Inicia L como uma matriz identidade
    L = Matrix(1.0I, rows, cols)
    for j = 1:cols
        non_zero_cols = j+1:cols
        for i = j+1:rows
            L[i, j] = U[i, j] / U[j, j]  # multiplicador que vai zerar a coluna
            U[i, non_zero_cols] -= L[i, j] * U[j, non_zero_cols]  # subtracao das linhas de A
            U[i, j] = 0  # zera cada elemento abaixo do pivô na coluna j
        end
    end
    return L, U
end

decomposicao_LU

#### Exemplo 1 (n = 3)

In [90]:
A = [45  6.777  -1.59;
      3      9   -0.1;
     10     45      1]

3×3 Matrix{Float64}:
 45.0   6.777  -1.59
  3.0   9.0    -0.1
 10.0  45.0     1.0

In [91]:
b = [9.0, 18.0, -75.1]

3-element Vector{Float64}:
   9.0
  18.0
 -75.1

In [92]:
L, U = decomposicao_LU(A)
L

3×3 Matrix{Float64}:
 1.0        0.0      0.0
 0.0666667  1.0      0.0
 0.222222   5.08809  1.0

In [93]:
U

3×3 Matrix{Float64}:
 45.0  6.777   -1.59
  0.0  8.5482   0.006
  0.0  0.0      1.3228

In [100]:
A - L * U

3×3 Matrix{Float64}:
 0.0   0.0          0.0
 0.0   0.0          0.0
 0.0  -7.10543e-15  0.0

#### Exemplo 2 (n = 5)

In [101]:
n = 5
A = rand(n,n)
b = rand(n)
L, U = decomposicao_LU(A)
A - L*U

5×5 Matrix{Float64}:
  0.0           0.0           0.0           0.0           0.0
  0.0           0.0           0.0           0.0           0.0
  0.0          -1.11022e-16  -1.11022e-16   0.0           0.0
  0.0           0.0           0.0          -2.77556e-17  -5.55112e-17
 -1.11022e-16   0.0          -5.55112e-17  -5.55112e-17  -5.77316e-15

#### Exemplo 3 (n = 20)

In [102]:
n = 20
A = rand(n,n)
b = rand(n)
L, U = decomposicao_LU(A)
A - L*U

20×20 Matrix{Float64}:
  0.0           0.0           0.0          …   0.0           0.0
 -1.11022e-16   0.0           0.0             -2.22045e-16   0.0
  0.0          -1.38778e-17   0.0             -2.77556e-17   1.38778e-17
  0.0           0.0           0.0              2.22045e-16   0.0
  0.0           0.0           0.0             -6.66134e-16   0.0
  0.0           0.0           0.0          …   0.0           0.0
  0.0           0.0          -1.11022e-16     -3.33067e-16  -1.11022e-16
  0.0           2.77556e-17   0.0             -7.77156e-16   3.33067e-16
  0.0           0.0           0.0              6.66134e-16  -1.04083e-16
  0.0           0.0           0.0             -4.44089e-16   2.22045e-16
  0.0           0.0           0.0          …  -1.11022e-16   0.0
  0.0           0.0           1.11022e-16     -6.66134e-16  -5.55112e-16
  0.0          -2.77556e-17   0.0              0.0          -8.32667e-17
  0.0          -5.55112e-17   0.0              2.22045e-16   6.66134e-16
  0

### Resolve Pós-LU 

In [104]:
# resolve pos-LU
"""
RESUMO: Esta funcao deve ser utilizada depois que fizemos uma decomposicao LU.
        Quando fazemos essa decomposicao LU em um sistema linear temos o seguinte:

        Ax = b
        LUx = b; y = Ux
        Ly = b
        y = L⁻¹b
        Ux = L⁻¹b
        x = U⁻¹L⁻¹b

        Esta funcao primeiro vai resolver o sistema Ly = b para depois resolver 
        o sistema Ux = y.
        A complexidade dessa funcao é apenas O(n²), contra O(n³) de uma eliminacao 
        gaussiana normal.

ENTRADA: Matriz L, Matriz U, Vetor b

SAIDA: Vetor x (solucao de LUx = b)
"""
function resolve_pos_LU(L, U, b)
    y = resolve_triangular_inferior(L, b)
    x = resolve_triangular_superior(U, y)
    return x
end

resolve_pos_LU

#### Exemplo 1 (n = 3)

In [105]:
L = [  1     0  0;
      23     1  0;
     -91  1.11  1]

3×3 Matrix{Float64}:
   1.0  0.0   0.0
  23.0  1.0   0.0
 -91.0  1.11  1.0

In [106]:
U = [6  70     -10
     0 241  99.999
     0   0      -1]

3×3 Matrix{Float64}:
 6.0   70.0  -10.0
 0.0  241.0   99.999
 0.0    0.0   -1.0

In [107]:
b = [64, 13.171, -0.4]

3-element Vector{Float64}:
 64.0
 13.171
 -0.4

In [110]:
x = resolve_pos_LU(L, U, b)

3-element Vector{Float64}:
 -48353.82279037807
   3082.2562120324064
  -7442.90019

In [112]:
norm(L * U * x - b)

3.326949296948146e-9

#### Exemplo 2 (n = 5)

In [115]:
n = 5
L = UnitLowerTriangular(rand(n,n))
U = UpperTriangular(rand(n,n))
b = rand(n)
x = resolve_pos_LU(L, U, b)
norm(L*U*x - b)

0.0

#### Exemplo 3 (n = 20)

In [119]:
n = 20
L = UnitLowerTriangular(rand(n,n))
U = UpperTriangular(rand(n,n))
b = rand(n)
x = resolve_pos_LU(L, U, b)
norm(L*U*x - b)

8.345230562421201e-12

### Acha inversa 

In [208]:
# Acha inversa
"""
RESUMO: Vamos achar a inversa de uma matriz A utilizando a decomposicao LU.
        Primeiro, vamos decompor A em L * U.
        Depois, vamos usar os vetores canonicos da matriz identidade como
        valores de b no sistema linear LUx = b.
        Ou seja, vamos descobrir os vetores que fazem parte da matriz inversa de A
        calculando um x para cada vetor na matriz identidade com as mesmas dimensoes que A.

ENTRADA: Matriz A

SAIDA: Matriz A⁻¹ (inversa de A)
"""
function acha_inversa(A)
    rows, cols = size(A)  # Pega as dimensoes de A
    L, U = decomposicao_LU(A)  # Faz a decomposicao LU
    A⁻¹ = []
    for i = 1:cols
        id_vector = zeros(cols)
        id_vector[i] = 1.0  # Monta cada coluna da identidade
        x = resolve_pos_LU(L, U, id_vector)  # resolve um sistema para cada coluna da identidade
        append!(A⁻¹, x)  # Adiciona os elemetos do vetor x numa array
    end
    A⁻¹ = reshape(A⁻¹, rows, cols)  # Formata a array como uma matriz quadrada
    return A⁻¹
end

acha_inversa

#### Exemplo 1 (n = 3)

In [209]:
A = [  2  49     -12;
     0.5  10       1;
      -9   0  54.888]

3×3 Matrix{Float64}:
  2.0  49.0  -12.0
  0.5  10.0    1.0
 -9.0   0.0   54.888

In [210]:
A⁻¹ = acha_inversa(A)

3×3 Matrix{Any}:
 -0.310453    1.52122     -0.0955885
  0.0206132  -0.00100453   0.0045249
 -0.0509051   0.249435     0.00254525

In [211]:
A * A⁻¹

3×3 Matrix{Any}:
  1.0          0.0          6.93889e-18
  2.08167e-17  1.0          8.67362e-18
 -2.66454e-15  1.06581e-14  1.0

#### Exemplo 2 (n = 5)

In [212]:
n = 5
A = rand(n,n)
b = rand(n)
A⁻¹ = acha_inversa(A)
A * A⁻¹ ≈ I

true

#### Exemplo 3 (n = 20)

In [213]:
n = 20
A = rand(n,n)
b = rand(n)
A⁻¹ = acha_inversa(A)
A * A⁻¹ ≈ I

true