In [5]:
using LinearAlgebra

In [6]:
function resolve_diagonal(D,b) #D é diagonal
    x=zeros(3,1)
    x[1]=b[1]/D[1,1]
    x[2]=b[2]/D[2,2]
    x[3]=b[3]/D[3,3]
    return x
end

resolve_diagonal (generic function with 1 method)

In [7]:
D=[2 0 0;0 4 0;0 0 194]

3×3 Matrix{Int64}:
 2  0    0
 0  4    0
 0  0  194

In [8]:
b=randn(3,1)

3×1 Matrix{Float64}:
  0.6092517148242524
 -0.12975120912135807
  1.454329668186886

In [9]:
x=resolve_diagonal(D,b)

3×1 Matrix{Float64}:
  0.3046258574121262
 -0.03243780228033952
  0.0074965446813757015

In [10]:
norm(D*x-b)

0.0

In [11]:
function resolve_triangular_superior(T,b) #T é triangular superior
    x=zeros(3,1)
    x[3]=b[3]/T[3,3]
    x[2]=(b[2]-T[2,3]*x[3])/T[2,2]
    x[1]=(b[1]-T[1,3]*x[3]-T[1,2]*x[2])/T[1,1]
    return x
end

resolve_triangular_superior (generic function with 1 method)

In [12]:
T=[1 2 3;0 2 3;0 0 1]

3×3 Matrix{Int64}:
 1  2  3
 0  2  3
 0  0  1

In [13]:
b=randn(3,1)

3×1 Matrix{Float64}:
  1.177575745495298
 -0.02987698138756808
  1.9153544120257548

In [14]:
x=resolve_triangular_superior(T,b)

3×1 Matrix{Float64}:
  1.2074527268828659
 -2.8879701087324166
  1.9153544120257548

In [15]:
norm(T*x-b)

5.129621610332541e-16

In [16]:
function resolve_triangular_inferior(L,b) #T é triangular inferior
    x=zeros(3,1)
    x[1]=b[1]/L[1,1]
    x[2]=(b[2]-L[2,1]*x[1])/L[2,2]
    x[3]=(b[3]-L[3,1]*x[1]-L[3,2]*x[2])/L[3,3]
    return x
    
end

resolve_triangular_inferior (generic function with 1 method)

In [17]:
function eliminação_gaussiana(A,b) #A é uma matriz cheia ("matriz densa")
    multiplicador=A[2,1]/A[1,1]
    A[2,:]=A[2,:]-multiplicador*A[1,:]  # O(n)
    b[2]=b[2]-multiplicador*b[1]
    
    multiplicador=A[3,1]/A[1,1]
    A[3,:]=A[3,:]-multiplicador*A[1,:]
    b[3]=b[3]-multiplicador*b[1]
    
    multiplicador=A[3,2]/A[2,2]
    A[3,:]=A[3,:]-multiplicador*A[2,:]
    b[3]=b[3]-multiplicador*b[2]
    
    return A,b
end

eliminação_gaussiana (generic function with 1 method)

In [18]:
A=[2 4 3;4 10 9;6 18 22]

3×3 Matrix{Int64}:
 2   4   3
 4  10   9
 6  18  22

In [19]:
b=[9; 23; 46]

3-element Vector{Int64}:
  9
 23
 46

In [20]:
A[1,2]

4

In [21]:
A[2,:]=A[2,:]-2*A[1,:]

3-element Vector{Int64}:
 0
 2
 3

In [22]:
A

3×3 Matrix{Int64}:
 2   4   3
 0   2   3
 6  18  22

In [23]:
A[3,:]=A[3,:]-3*A[1,:]

3-element Vector{Int64}:
  0
  6
 13

In [24]:
A

3×3 Matrix{Int64}:
 2  4   3
 0  2   3
 0  6  13

In [25]:
A[3,:]=A[3,:]-3*A[2,:]

3-element Vector{Int64}:
 0
 0
 4

In [26]:
A

3×3 Matrix{Int64}:
 2  4  3
 0  2  3
 0  0  4

In [27]:
T,c= eliminação_gaussiana(A,b)

([2 4 3; 0 2 3; 0 0 4], [9, 23, 46])

In [28]:
T

3×3 Matrix{Int64}:
 2  4  3
 0  2  3
 0  0  4

In [29]:
c

3-element Vector{Int64}:
  9
 23
 46

In [30]:
function resolve_cheia(A,b)
    T,c= eliminação_gaussiana(A,b)  #O(n^3)
    x=resolve_triangular_superior(T,b)  #O(n^2)
    return x
end

resolve_cheia (generic function with 1 method)

In [31]:
x=resolve_cheia(A,b)
A*x-b

3×1 Matrix{Float64}:
 0.0
 0.0
 0.0

In [32]:
function decomposição_LU(A) #A é uma matriz cheia ("matriz densa")
    L=zeros(3,3)
    L[1,1]=1
    L[2,2]=1
    L[3,3]=1
    
    L[2,1]=A[2,1]/A[1,1]
    A[2,:]=A[2,:]-L[2,1]*A[1,:]  # O(n)
   
    
    L[3,1]=A[3,1]/A[1,1]
    A[3,:]=A[3,:]-L[3,1]*A[1,:]

    
    L[3,2]=A[3,2]/A[2,2]
    A[3,:]=A[3,:]-L[3,2]*A[2,:]
    
    return L,A   
end

decomposição_LU (generic function with 1 method)

In [33]:
A=randn(3,3)

3×3 Matrix{Float64}:
  0.482017   0.31169     -0.787056
 -0.531015  -0.108959     1.80228
 -1.44784   -0.00822293  -0.395539

In [34]:
L,U=decomposição_LU(A)

([1.0 0.0 0.0; -1.1016521958232108 1.0 0.0; -3.0037055043429777 3.9587997854528743 1.0], [0.48201666260011017 0.3116903993232587 -0.7870556362174784; 0.0 0.23441529963638824 0.9352136934499659; 0.0 0.0 -6.461946428767323])

In [35]:
L

3×3 Matrix{Float64}:
  1.0      0.0     0.0
 -1.10165  1.0     0.0
 -3.00371  3.9588  1.0

In [36]:
U

3×3 Matrix{Float64}:
 0.482017  0.31169   -0.787056
 0.0       0.234415   0.935214
 0.0       0.0       -6.46195

In [37]:
A-L*U

3×3 Matrix{Float64}:
 0.0       0.0          0.0
 0.531015  0.343374    -0.867062
 1.44784   0.00822293  -6.06641

In [38]:
A=[2 4 3;4 10 9;6 18 22]

3×3 Matrix{Int64}:
 2   4   3
 4  10   9
 6  18  22

In [39]:
A_original=[2 4 3;4 10 9;6 18 22]

3×3 Matrix{Int64}:
 2   4   3
 4  10   9
 6  18  22

In [40]:
L,U=decomposição_LU(A)

([1.0 0.0 0.0; 2.0 1.0 0.0; 3.0 3.0 1.0], [2 4 3; 0 2 3; 0 0 4])

In [41]:
L

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 2.0  1.0  0.0
 3.0  3.0  1.0

In [42]:
U

3×3 Matrix{Int64}:
 2  4  3
 0  2  3
 0  0  4

In [43]:
L*U

3×3 Matrix{Float64}:
 2.0   4.0   3.0
 4.0  10.0   9.0
 6.0  18.0  22.0

In [44]:
A_original-L*U

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [45]:
function resolver_pós_LU(L,U,b)    #O(n^2) 
    y=resolve_triangular_inferior(L,b)
    x=resolve_triangular_superior(U,y)
    return x
end

resolver_pós_LU (generic function with 1 method)

In [46]:
function achar_inversa(A)
    L,U=decomposição_LU(A)
    x1=resolver_pós_LU(L,U,[1;0;0]) 
    x2=resolver_pós_LU(L,U,[0;1;0]) 
    x3=resolver_pós_LU(L,U,[0;0;1])
    return [x1 x2 x3]
end  

achar_inversa (generic function with 1 method)

In [47]:
A=randn(3,3)

3×3 Matrix{Float64}:
 -0.479083   0.151541   2.05813
 -0.36287    0.82595    0.856023
 -0.997107  -0.0585793  0.435153

In [48]:
A=[2 4 3;4 10 9;6 18 22]

3×3 Matrix{Int64}:
 2   4   3
 4  10   9
 6  18  22

In [49]:
A_original=[2 4 3;4 10 9;6 18 22]

3×3 Matrix{Int64}:
 2   4   3
 4  10   9
 6  18  22

In [50]:
M=achar_inversa(A)

3×3 Matrix{Float64}:
  3.625  -2.125   0.375
 -2.125   1.625  -0.375
  0.75   -0.75    0.25

In [51]:
A_original*M

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0